### ISSUE TITLE
Installation ok mais pas tous les capteurs 

### ISSUE THREAD

**Issue by oli6120** [dathosim/HomeAssistant-Freebox-Pack-Securite#10]
Bonjour Monsieur,

J'ai bien réussi à installer votre adon Freebox sur le nod-RED il fonctionne bien, et est connecté.

![Capture d’écran 2023-11-25 à 15 21 56](https://github.com/dathosim/HomeAssistant-Freebox-Pack-Securite/assets/91420931/3ed5efa6-6884-45c5-aa87-0da8f3074152)

Les messages MQTT passent bien aussi sans aucun problème.

Par contre là où je rencontre un petit souci ce sont dans les entités. Il ne me détecte que les sensors (le motion et le capteur ouvert fermé (fenêtre ou porte)) ainsi que l'état de la batterie de la télécommande.

![Capture d’écran 2023-11-25 à 15 30 13](https://github.com/dathosim/HomeAssistant-Freebox-Pack-Securite/assets/91420931/6a405818-4592-4d8d-a649-04f6fa263ced)
![Capture d’écran 2023-11-25 à 15 30 23](https://github.com/dathosim/HomeAssistant-Freebox-Pack-Securite/assets/91420931/4ff93083-364c-4fac-8a1d-99d5324e5a48)
![Capture d’écran 2023-11-25 à 15 30 32](https://github.com/dathosim/HomeAssistant-Freebox-Pack-Securite/assets/91420931/94889819-ee95-4902-be58-99daabf5435a)

Je n'ai pas la "centrale" avec l'état de l'alarme (activé ou désactivé) et la possibilité de l'enclencher. Sous quelle "entité ou autre" la centrale d'alarme est elle implémentée ?

Avez vous deja eu ce type de souci? si oui comment peut-on le résoudre?
Je peux vous fournir les infos dont vous avez besoin si nécessaire.
Cordialement 

Olivier

**Comment by dathosim** [comment]
Bonjour @oli6120,
alors en fait je ne maintiens plus trop cette "pseudo" intégration car sa mise en oeuvre est complexe (NodeRed, MQTT + du code à maintenir avec un API un évolue et des yaml..) bref
Je conseille depuis un moment de passer par l'intégration Freebox_home qui est dispo via HACS
Vous connaissez HACS ? il faut l'installer d'abord : 
https://hacs.xyz/docs/configuration/basic 
Et ensuite installer : https://github.com/gvigroux/freebox_home
Et ça correspond tout a fait à ce qui manque à l'extension officielle pour gérer l'alarme, et les détecteurs du pack sécurité !
