### ISSUE TITLE
Au top !!! Merciiiiiiiiiiiii !!!

### ISSUE THREAD

**Issue by Dgigie** [dathosim/HomeAssistant-Freebox-Pack-Securite#6]
Je débute avec Home Assistant et node red, à l'heure actuelle et grace à toi, j'ai réussi à me connecter à ma Freebox Delta, son pack Securité et tout fonctionne bien.
Je souhaiterais ajouter une autre Freebox, une V6 que je gère à distance.
J'ai fais quelques tentatives en reprenant le "package node-red-contrib-freebox" mais quand j'essaye de créer un nouveau Flow en reprenant les mêmes nodes et en changeant les paramètres pour accéder à ma 2ème box, ça plante...
Node red m'affiche la fameuse erreur 502 et mon flow freebox bug... 
J'essaye d'interroger la V6 via son IP publique et je ne sais pas si d'une part c'est possible et d'autre part pour le serveur HA je met l'adresse que j'utilise via duckdns.org... En somme je ne suis sur de rien pour l'instant...
Après de multiples tentatives, à l'heure actuelle, je désespère...
Aurais-tu une solution ?
Merciiiiiiii......

**Comment by dathosim** [comment]
Hello
merci pour tes retours ! 
Je suis en train de refaire complètement le flow NodeRed que j'avais fait et dont je me servais plus...
Car depuis je sais envoyer aussi des infos depuis Home assistant dans NodeRed et contrôler la Freebox : exemple pour activer ou éteindre le wifi

Aussi pour ton problème il faut t'assurer que la box est contactable a distance : via un host en https://xxxxx.freeboxos.fr par exemple (ou ton propre domaine) et le port spécifique que tu auras configuré pour l'accès à distance 
Exemple : https://ton_sous_domaine.freeboxos.fr:88888
88888 : étant ton port d'accès distant sécurisé

La configuration des ports pour l'accès externe se faite dans FreeboxOS : 
Paramètre de la Freebox > Configuration > Port accès distant sécurisé 

La configuration pour l'accès via le domaine freeboxos.fr se fait aussi dans FreeboxOS:  
Paramètre de la Freebox > Nom de domaine > ajouter un nom de domaine

Ensuite, tu te connectes à distance via cette adresse et ce port et tu testes que tu peux accéder à l'API depuis internet et donc depuis ton Home assistant qui est hébergé à un autre endroit
Exemple d'adresse a saisir dans ton navigateur : https://ton_sous_domaine.freeboxos.fr:88888/api/v10/system/

Vérifie déjà ça tout ça avant de tenter de le faire depuis nodeRed

**Comment by Dgigie** [comment]
Salut,
tout d'abord un grand merci pour ta réponse, ça fait toujours plaisir que quelqu'un vienne te "secourir" avant que tu ne prennes un marteau pour tout casser :-)

J'avais deja tout fait pour ce qui est de l'accès à distance, nom de domaine etc.. et ça fonctionne car via ton exemple https://ton_sous_domaine.freeboxos.fr:88888/api/v10/system/ j'ai bien une remontée d'information.

Mon souci c'est surtout comment ajouter cette 2ème freebox sur node red.

J'ai bien essayé en prenant les mêmes modules que ceux qui fonctionnent avec ma Delta

![NR](https://user-images.githubusercontent.com/128133018/231131642-3b778dc3-8a61-49f7-84df-bc92163aab6d.JPG)

mais je dois faire des conneries car quand je mets certains paramètres cela modifie ceux de la freebox deja présente et qui du coup ne fonctionne plus.

Faut il que j'installe un 2ème package node-red-contrib-freebox ? si oui je ne vois pas comment faire sur NR.

Je pense que l'adresse /home/tileset/all que je mets dans l'injection renvoi directement à ma 1ère box.

Après je suis trop novice pour savoir quelle adresse je dois mettre dans mon nouveau Flow.

Voila j'en suis là... :-)

En tout cas encore un grand merci !!!

**Comment by dathosim** [comment]
Hello merci. pour ton retour

et bien quand tu créé un noeud connection ou api (du type de noeud Freebox) dans NodeRed, tu dois créer un server 
Et la du créé un nouveau serveur avec une autre URL : celle de ton accès distant à la 2eme Freebox 
![Capture d’écran 2023-04-13 à 18 40 10](https://user-images.githubusercontent.com/47037724/231827395-45645d6a-3b82-4b61-99ed-be37033a6a54.png)

**Comment by Dgigie** [comment]
Ok prof !!! :-)
J'avais tenté un truc comme ça en changeant le serveur mais je crois que ça modifiait le flow deja existant le la 1ère Box.... enfin bon j'ai peut être aussi fait n'importe quoi...
Ce weekend si j'ai du temps vais retenter de créer un nouveau flow...
Du coup je reviendrai vers toi soit pour te remercier une fois de plus, soit pour prendre rdv pour une nouvelle consultation... :-)))
Bonne soirée et encore merci à toi

**Comment by Dgigie** [comment]
Bon bah je bloque sur ce que je dois mettre à l'injection.... 
Le pire c'est qu'à chaque fois ça me fait bugger Node Red.... erreur 502... même en supprimant tout mon nouveau flow je suis obligé de remettre une sauvegarde....
ça va finir au marteau cette histoire.... je désespère.....
Le pire c'est que je ne veux "QUE" récupérer des modules shelly qui sont connectés à cette V6 car l'integration Shelly ne prend en compte que les modules qui sont sur le même réseau que HA....

**Comment by Dgigie** [comment]
Salut,
Bon j'espère que tu es en forme et que tu fais plein de codages :-)
sinon depuis cette après midi et depuis la dernière mise à jour de node red j'ai un petit soucis avec api de la delta

![Capture](https://github.com/dathosim/HomeAssistant-Freebox-Pack-Securite/assets/128133018/b50196f2-c9aa-4596-83b9-99937e23ff73)


Bizarrement la delta semble toujours connectée et à l'air de toujours fonctionner malgré ça...
Pourtant l'API est en "erreur"...

Quoi qu'il en soit cela dépasse mon niveau de compétence car je n'ai rien touché ni rien modifié depuis pas mal de temps car tout fonctionnait parfaitement. J'ai fais un redémarrage complet de HA mais l'erreur est toujours là...

Si tu as une explication et éventuellement une solution je t'avoue que je suis preneur...

Bonne soirée

**Comment by dathosim** [comment]
désolé pour le retour tardif mais je pense que cela soit un problème local que je ne reproduit pas

**Comment by Dgigie** [comment]
Merci pour ton retour,

De mon coté je n'ai touché à rien, j'ai tout revérifié et je ne trouve rien d'anormal, depuis il y a eu plusieurs MAJ de Node Red et l'erreur est toujours présente, malgré tout cela continue de fonctionner parfaitement....

Donc pour moi c'est le plus important, tant que ça marche... :-)

Encore merci et passe un bon weekend.
