### ISSUE TITLE
Import Fichier de flow

### ISSUE THREAD

**Issue by Typi4k** [dathosim/HomeAssistant-Freebox-Pack-Securite#9]
Bonjour,

Tout d'abord merci du travail effectué sur ce projet. 
Mais je rencontre un soucis pour importer votre fichier.json de flow dans node-red, j'obtiens une erreur en me signalant que ce n'est pas un fichier valide donc je peux pas valider l'import.

Avez-vous une solution ? Merci d'avance !!

![Capture d'écran 2023-10-08 175246](https://github.com/dathosim/HomeAssistant-Freebox-Pack-Securite/assets/147332941/79d10ea5-df00-4bad-a4ce-ca30f377e9dd)

**Comment by dathosim** [comment]
désolé pour la réponse tardive 😩
mais vous tentez d'importer le fichier HTML  
il faut cliquer sur bouton "raw" dans Github et ensuite downloader le fichier qui doit être un json
je clot l'issue
